server:
  port: 8002
spring:
  application:
    name: rookie-nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址



management:
  endpoints:
    web:
      exposure:
        include: '*'

